// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqEF-7JjKJeBJ2U1iVAP3y1OKqHrcED4Y',
    appId: '1:725323482577:web:ea08852af4129ca68d4cf0',
    messagingSenderId: '725323482577',
    projectId: 'taru-673bb',
    authDomain: 'taru-673bb.firebaseapp.com',
    storageBucket: 'taru-673bb.firebasestorage.app',
    measurementId: 'G-P05YEWH6GY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb0WfEVc-7DUkStKNYMLWODSjp_Rk1nYU',
    appId: '1:725323482577:android:fdd693352a3e21d58d4cf0',
    messagingSenderId: '725323482577',
    projectId: 'taru-673bb',
    storageBucket: 'taru-673bb.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKIaUj_oXQ-9Z055kwmyYVxfn1MPAIBXc',
    appId: '1:725323482577:ios:363b5f331c63d0b38d4cf0',
    messagingSenderId: '725323482577',
    projectId: 'taru-673bb',
    storageBucket: 'taru-673bb.firebasestorage.app',
    iosBundleId: 'com.taru.health',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKIaUj_oXQ-9Z055kwmyYVxfn1MPAIBXc',
    appId: '1:725323482577:ios:363b5f331c63d0b38d4cf0',
    messagingSenderId: '725323482577',
    projectId: 'taru-673bb',
    storageBucket: 'taru-673bb.firebasestorage.app',
    iosBundleId: 'com.taru.health',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqEF-7JjKJeBJ2U1iVAP3y1OKqHrcED4Y',
    appId: '1:725323482577:web:0db95dcda2fe45798d4cf0',
    messagingSenderId: '725323482577',
    projectId: 'taru-673bb',
    authDomain: 'taru-673bb.firebaseapp.com',
    storageBucket: 'taru-673bb.firebasestorage.app',
    measurementId: 'G-95B5BQMR59',
  );
}
